services:

  api:
    build: ./api/.
    container_name: ss-api
    volumes:
      - ./api/src:/api/src
    ports:
      - "${API_PORT}:8080"
    env_file:
      - .env
    tty: true
    depends_on:
      - database
    networks:
      - api-to-database

  database:
    image: postgres:15
    container_name: ss-database
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - api-to-database

networks:
  api-to-database: