services:

  api:
    build: ./project/api/.
    container_name: ss-api
    volumes:
      - ./project/api/src:/api/src
    ports:
      - "${API_PORT}:25000"
    environment:
      - PYTHONUNBUFFERED=1 # Avoid duplication in writes on STDOUT
    env_file:
      - .env
    tty: true
    depends_on:
      - database
    networks:
      - api-to-database

  database:
    image: postgres:15
    container_name: ss-database
    env_file:
      - .env
    volumes:
      - ./project/database/data:/var/lib/postgresql/data
    networks:
      - api-to-database

networks:
  api-to-database: